### ISSUE TITLE
Issues rendering with tabs

### ISSUE THREAD

**Issue by sezna** [timothee-haudebourg/source-span#5] opened 2021-05-09 14:04 UTC
Hi! This is an amazing tool, thank you for your work in bringing it to the rust ecosystem. 

I'm encountering an issue when trying to render text with tabs. It seems that source-span will count the tabs as single-width characters, when in reality it should probably track both single width and tab-width characters for proper padding. 

I've attached a screenshot of what I'm talking about -- the red error span should be on the `==`, and it is on the `==` when I replace the tabs with spaces.

<img width="486" alt="Screen Shot 2021-05-09 at 9 03 46 AM" src="https://user-images.githubusercontent.com/12157751/117575013-91f86680-b0a5-11eb-9908-40aee859f3f2.png">

**Comment by timothee-haudebourg** [comment] 2021-05-09 18:43
Hi,

Do you think you could provide a minimal example that reproduces your problem? I haven't been able to reproduce it on my side.

**Comment by emilyaherbert** [comment] 2021-10-04 19:57
Below is an example of code that generates the bug, where the whitespace in front of `String` is `\t`.

```
enum NumberOrString {
    Number: u64,
	String: str[4],
}
```

**Comment by emilyaherbert** [comment] 2021-10-04 21:20
To be clear, I've placed the above code in `fix.txt` to reproduce the issue. I generates this bug with the placement of brackets, but I suspect that the issue is in calculating the span maybe? I will look into it as well.

<img width="1440" alt="Screen Shot 2021-10-04 at 4 17 45 PM" src="https://user-images.githubusercontent.com/17410721/135926339-c491a751-afd2-4268-8575-fce81f53dddb.png">

**Comment by timothee-haudebourg** [comment] 2021-10-04 21:46
That's weird. I'm still not able to reproduce that. Your example works fine when I try it.
```
 1 | /     enum NumberOrString {
   | |    _____________________^
 2 | |   |     Number: u64,
 3 | |   |         String: str[4],                          
   | |   |                    ^^^ this is a pair of brackets
 4 | |   | }                         
   | |   |_^ this is a pair of braces
```
What version of the crate are you using? Does it work without changing `fib.txt`? Note how `String` is not aligned the same on your side and mine. Did you change `examples/formatting.rs` as well? Are you using the default character metrics?

**Comment by timothee-haudebourg** [comment] 2021-10-04 21:47
Can you copy/paste the exact output? Maybe there is a `\t` in the formatted output (I don't see how that could happen but let's see...).

**Comment by emilyaherbert** [comment] 2021-10-04 21:52
- I'm using the latest version.
- If I run the example without adding the enum, it still does not work for the other strings, etc.
- I haven't changed `examples/formatting.rs`
- What do you mean by default character metrics? I cloned the repo and haven't really touched the example.

What version of Rust are you using?

```
 1 | /     enum NumberOrString {
   | |    _____________________^
 2 | |   |     String2: str[4],                          
   | |   |                 ^^^ this is a pair of brackets
 3 | |   | 	       String1: str[4],                          
   | |   |                     ^^^ this is a pair of brackets
 4 | |   | }                         
   | |   |_^ this is a pair of braces
 5 | |
 6 | |     pub fn fibonacci(n: i32) -> u64 {                   
   | |                     --------        ^                   
   | |  __________________________|________|                   
   | | |                          |                            
   | | |                          this is a pair of parenthesis
 7 | | |   	       if n < 0 {
   | | |  __________________^
 8 | | | | 	       	       panic!("{} is negative!", n);                             
   | | | |                       -"^^             "   - this is a pair of parenthesis
   | | | |                       ||_|_____________|   |                              
   | | | |                       |__|_____________|___|                              
   | | | |                          |             |                                  
   | | | |                          |             this is a string                   
   | | | |                          |                                                
   | | | |                          this is a pair of braces                         
 9 | | | | 	       } else if n == 0 {      
   | | | |_________^                ^      
   | | |  _________|________________|      
   | | | |         |                       
   | | | |         this is a pair of braces
10 | | | | 	       	       panic!("zero is not a right argument to fibonacci()!");                             
   | | | |                       -"                                         -- "- this is a pair of parenthesis
   | | | |                       ||__________________________________________|_||                              
   | | | |                       |___________________________________________|_||                              
   | | | |                                                                   | |                               
   | | | |                                                                   | this is a string                
   | | | |                                                                   |                                 
   | | | |                                                                   this is a pair of parenthesis     
11 | | | | 	       } else if n == 1 {      
   | | | |_________^                ^      
   | | |           |                |      
   | | |  _________|________________|      
   | | | |         |                       
   | | | |         this is a pair of braces
12 | | | | 	       	       return 1;
13 | | | | 	       }                         
   | | | |_________^ this is a pair of braces
14 | | |
15 | | |   	       let mut sum = 0;
16 | | |   	       let mut last = 0;
17 | | |   	       let mut curr = 1;
18 | | |   	       for _i in 1..n {
   | | |  ________________________^
19 | | | | 	       	       sum = last + curr;
20 | | | | 	       	       last = curr;
21 | | | | 	       	       curr = sum;
22 | | | | 	       }                         
   | | | |_________^ this is a pair of braces
23 | | |   	       sum
24 | | |   }                           
   | | |___^^ this is the whole program
   | |_____|| what a nice program!     
   |       |                           
   |       this is a pair of braces    
25 |
```

**Comment by timothee-haudebourg** [comment] 2021-10-04 21:57
Oh yeah, there is a `\t` in the formatted output that should not be there.

**Comment by timothee-haudebourg** [comment] 2021-10-05 20:02
What OS are you on? What version of Rust are you using? (I'm on 1.54.0). I don't understand how a `\t` can get there, and I don't have this issue on my side. Tabs are explicitly ignored during render to avoid this issue.
https://github.com/timothee-haudebourg/source-span/blob/ee9981629dee9fd184f81791f3699d0b8562a8c4/src/fmt.rs#L1032

One may argue that I should ignore all control characters to be sure, but at least this case should be covered. I'm missing something here.

**Comment by timothee-haudebourg** [comment] 2021-10-05 20:06
By "ignored" in that case I mean that they are replaced by the necessary amount of white-spaces needed to reach the next tab stop (whose length is given by the [character metrics](https://docs.rs/source-span/2.7.0/source_span/trait.Metrics.html), by default 8).

**Comment by sezna** [comment] 2021-10-05 21:02
I originally encountered this on Ubuntu.

I think your pattern match should be triggering - https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c11f23fbebce8dd4cf59685fb4c87123

Edit: Mac OS seems to not have the same issue

**Comment by timothee-haudebourg** [comment] 2021-10-05 21:24
Can you explain your example? I get exactly what I expected:

```
tab control sequence matches: true
unicode tab matches: true
```

`\t` should be equivalent to `\u{0009}`, or do you mean some systems use a different encoding for `\t` I am not aware of?

**Comment by sezna** [comment] 2021-10-05 21:57
Hey Timothee, sorry, I provided that example to support your claim. I did not figure out why `\t` wasn't matching -- I meant that it appears that it _should_ be matching.

**Comment by timothee-haudebourg** [comment] 2021-10-05 22:25
What a weird issue. I wish I could debug on your machine. Could you add a `assert_ne!(c, '\t')` in the default case? In this block:
https://github.com/timothee-haudebourg/source-span/blob/ee9981629dee9fd184f81791f3699d0b8562a8c4/src/fmt.rs#L1033

**Comment by emilyaherbert** [comment] 2021-10-11 16:21
Well, this is weird. My `zsh` updated and now everything is rendering properly...

**Comment by emilyaherbert** [comment] 2021-10-11 16:22
> Could you add a `assert_ne!(c, '\t')` in the default case? In this block:

I added this and it was silent---nothing happened.

**Comment by timothee-haudebourg** [comment] 2021-10-11 16:25
> My zsh updated and now everything is rendering properly

How is that even possible? Well I'm closing for now since I'm unable to reproduce and zsh was the problem for some impossible reason. Don't hesitate to reopen if you see this behavior again.

**Closed as completed by timothee-haudebourg** 2021-10-11 16:25 UTC
